### ISSUE TITLE
Usage with Webpack

### ISSUE THREAD

**Issue by dvdbrk** [bradmartin/nativescript-videoplayer#71]
So if I run the app with `tns run android` both local file and remote files are played.
However, using `npm run start-android-bundle --aot`, same path to local file (~/assets/videos/test.mp4) gives an error:

```JS: Openvideo assets/images/bg_video_3.mp4
JS: Error: Error: java.io.IOException: setDataSource failed.
JS:     android.media.MediaPlayer.setDataSource(MediaPlayer.java:1093)
JS:     android.media.MediaPlayer.setDataSource(MediaPlayer.java:1039)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:890)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:874)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:866)
JS:     com.tns.gen.android.view.TextureView_SurfaceTextureListener.onSurfaceTextureAvailable(TextureView_SurfaceTextureListener.java:13)
JS:     android.view.TextureView.getHardwareLayer(TextureView.java:390)
JS:     android.view.TextureView.draw(TextureView.java:339)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.draw(View.java:17188)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.draw(View.java:17188)
JS:     com.android.internal.policy.DecorView.draw(DecorView.java:753)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
JS:     android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
JS:     android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
JS:     android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
JS:     android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
JS:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
JS:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
JS:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
JS:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
JS:     android.view.Choreographer.doCallbacks(Choreographer.java:686)
JS:     android.view.Choreographer.doFrame(Choreographer.java:621)
JS:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6119)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) Error: java.io.IOException: setDataSource failed.
JS:     android.media.MediaPlayer.setDataSource(MediaPlayer.java:1093)
JS:     android.media.MediaPlayer.setDataSource(MediaPlayer.java:1039)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1021)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:903)
JS:
JS:    com.tns.Runtime.callJSMethod(Runtime.java:890)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:874)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:866)
JS:     com.tns.gen.android.view.TextureView_SurfaceTextureListener.onSurfaceTextureAvailable(TextureView_SurfaceTextureListener.java:13)
JS:     android.view.TextureView.getHardwareLayer(TextureView.java:390)
JS:     android.view.TextureView.draw(TextureView.java:339)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.draw(View.java:17188)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16162)
JS:     android.view.View.draw(View.java:16951)
JS:     android.view.ViewGroup.drawChild(ViewGroup.java:3727)
JS:     android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
JS:     android.view.View.draw(View.java:17188)
JS:     com.android.internal.policy.DecorView.draw(DecorView.java:753)
JS:     android.view.View.updateDisplayListIfDirty(View.java:16167)
JS:     android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
JS:     android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
JS:     android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
JS:     android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
JS:     android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
JS:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
JS:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
JS:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
JS:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
JS:     android.view.Choreographer.doCallbacks(Choreographer.java:686)
JS:     android.view.Choreographer.doFrame(Choreographer.java:621)
JS:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6119)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
JS:     at Video.module.exports.webpackJsonp.194.Video._openVideo (file:///data/data/org.nativescript.Nativeapp/files/app/bundle.js:3695:30)
JS:     at Object.onSurfaceTextureAvailable (file:///data/data/org.nativescript.Nativeapp/files/app/bundle.js:3491:28)

**Comment by bnussey** [comment]
Thanks @dvdbrk are you also able to test on iOS to see if any related issues? Will investigate and provide fix.

**Comment by dvdbrk** [comment]
Solved. The problem was with Webpack - content of the assets folder was not being included in the bundle. So if anyone is experiencing the same, check your webpack config. It should include something like (webpack.common.js):

```
// Copy assets to out dir. Add your own globs as needed.
new CopyWebpackPlugin([
  { from: "app.css" },
  { from: "css/**" },
  { from: "assets/**" },
  { from: "fonts/**" },
  { from: "**/*.jpg" },
  { from: "**/*.png" },
  { from: "**/*.xml" },
], { ignore: ["App_Resources/**"] }),
